[build-system]
requires = [
    "setuptools>=64",
    "wheel",
    "torch",
]
build-backend = "setuptools.build_meta"


[project]
name = "flex_gemm"
version = "1.0.0+rocm"
description = "A Cross-Platform Backend for High-Performance Sparse Convolutions (ROCm)"
requires-python = ">=3.8"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Jianfeng Xiang", email = "belljig@outlook.com" },
    { name = "Michael Lamothe", email = "michael.lamothe@gmail.com" }
]
dependencies = [
    "torch>=2.4.0",
    "triton>=3.2.0; platform_system != 'Windows'",
    "triton-windows>=3.2.0; platform_system == 'Windows'",
    "filelock",
]
